apiVersion: v1
kind: Template
version: v1alpha1
metadata:
  name: cert-operator-template
objects:
- kind: CustomResourceDefinition
  apiVersion: apiextensions.k8s.io/v1beta1
  metadata:
    name: cert-operators.openshift.io
  spec:
    group: openshift.io
    version: v1alpha1
    names:
      kind: Cert-Operator
      listKind: Cert-OperatorList
      plural: cert-operators
      singular: ${APPLICATION_NAME}
    scope: Namespaced
- kind: Cert-Operator
  apiVersion: openshift.io/v1alpha1
  metadata:
    name: ${APPLICATION_NAME}
- kind: Deployment
  apiVersion: apps/v1beta1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAM}
  spec:
    replicas: 1
    selector:
        matchLabels:
          app: ${APPLICATION_NAM}
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAM}
      spec:
        serviceAccountName: ${SERVICE_ACCOUNT_NAME}
        containers:
        - name:  ${APPLICATION_NAM}
          image: docker-registry.default.svc:5000/${NAMESPACE}/${APPLICATION_NAM}:${TAG}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cert-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: ${APPLICATION_NAM}
            - name: NOTIFIER_TYPE
              value: ${NOTIFIER_TYPE}
            - name: WEBHOOK_URL
              value: ${WEBHOOK_URL}
            - name: VENAFI_API_URL
              value: ${VENAFI_API_URL}
            - name: VENAFI_USER_NAME
              value: ${VENAFI_USER_NAME}
            - name: VENAFI_PASSWORD
              value: ${VENAFI_PASSWORD}
            - name: VENAFI_CERT_ZONE
              value: ${VENAFI_CERT_ZONE}
parameters:
- description: "The name assigned to all of the frontend objects defined in this template."
  displayName: "Name"
  name: APPLICATION_NAME
  required: true
  value: "cert-operator"
- description: "Namespace in which the ImageStreams for operator images are
    installed. You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project."
  name: NAMESPACE
  required: true
  value: "infrastructure-jobs"
- description: "The tag for the iamge"
  name: TAG
  displayName: "Image Tag"
  required: true
  value: "latest"
- description: "The Venafi API URL"
  name: VENAFI_API_URL
  value: "https://venafi-tppurl/vedsdk"
  required: true
- description: "The Venafi user name"
  name: VENAFI_USER_NAME
  value: "venafiusername"
  required: true
- description: "The Venafi password"
  name: VENAFI_PASSWORD
  value: "venafipassword"
  required: true
- description: "The Venafi cert zone"
  name: VENAFI_CERT_ZONE
  value: "ABC Company\\Dev"
  required: true
- description: "The Slack webhook"
  name: WEBHOOK_URL
  value: "http://hooks.slack.com/services/..."
  required: false
- description: "Notifier type"
  name: NOTIFIER_TYPE
  value: "slack"
  required: false
- description: "Service account name"
  name: SERVICE_ACCOUNT_NAME
  value: "serviceaccountname"
  required: true